# Generated by Django 5.2.13 on 2026-04-17 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_billsplit_billsplitmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('p2p', 'Peer-to-Peer'), ('merchant', 'Merchant Payment'), ('bill', 'Bill Payment'), ('recharge', 'Mobile Recharge'), ('referral', 'Referral Bonus')], default='p2p', max_length=15),
        ),
    ]
