# Generated by Django 5.2.13 on 2026-04-15 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=20, unique=True)),
                ('ifsc', models.CharField(max_length=11)),
                ('upi_id', models.CharField(max_length=50, unique=True)),
                ('upi_pin', models.CharField(max_length=6)),
                ('balance', models.DecimalField(decimal_places=2, default=1000.0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
