# Generated by Django 5.2.13 on 2026-04-15 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_type', models.CharField(choices=[('mobile', 'Mobile Recharge'), ('electricity', 'Electricity Bill'), ('dth', 'DTH'), ('broadband', 'Broadband')], max_length=20)),
                ('biller_name', models.CharField(max_length=100)),
                ('customer_id', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(default='success', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
