# Generated by Django 5.2.13 on 2026-04-17 04:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='billpayment',
            name='bill_type',
            field=models.CharField(choices=[('mobile', 'Mobile Recharge'), ('electricity', 'Electricity Bill'), ('dth', 'DTH'), ('broadband', 'Broadband'), ('rent', 'Rent'), ('other', 'Other')], max_length=20),
        ),
        migrations.CreateModel(
            name='PaymentReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('due_date', models.DateField()),
                ('category', models.CharField(choices=[('mobile', 'Mobile Recharge'), ('electricity', 'Electricity Bill'), ('dth', 'DTH'), ('broadband', 'Broadband'), ('rent', 'Rent'), ('other', 'Other')], max_length=20)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
